### ISSUE TITLE
policy data on the repo

### ISSUE THREAD

**Issue by jerabaul29** [metno/MachineOcean-WP12#11]
@vkbo as we discussed there is the question of the data on the repo:

- would be great to have a bit of data available, so that 1) the scripts are fully functional, 2) we can later on integrate tests etc
- at the same time, I think that most of the data we use is not publicly available otherwise at the moment, for example the storm surge data.

For now I have put a symlink in the data folder on the repo. This means of course things work on my machine, but not on clones.

I think a simple solution may be to set up a separate submodule for the data, hosted privately on Met gitlab, similar to what is used for the config file. What do you think about that / would you be ok to set it up?

In this case, we could have a submodule for the whole ```example_data``` folder maybe, as this would be the simplest (rather than separating public vs non public data, we treat for now all data as non public)?

**Comment by vkbo** [comment]
> I think a simple solution may be to set up a separate submodule for the data, hosted privately on Met gitlab, similar to what is used for the config file. What do you think about that / would you be ok to set it up?

Agreed.

This solution also avoids bloating this repo with data.
