### ISSUE TITLE
question about the use_atm=True default argument

### ISSUE THREAD

**Issue by jerabaul29** [metno/MachineOcean-WP12#20]
@setmar here:

https://github.com/metno/MachineOcean-WP12/blob/72072ebed8ff2610748b55e4c6bc0c8d9d9aa94a/scripts/NORA3_ERA5/NORA3_ERA5.py#L116

What is the motivation for hvaing the ```use_atm=True``` default argument? If I refactor the code for the analysis of the Uppsala data, is it ok that I just remove this parameter and the associated logics, making the logics becoming equivalent to "this parameter is like it is always True"? :) .

**Comment by setmar** [comment]
I think some parameters are found both in the atm and the wave files, and that this argument is used to choose which source file set you want to use.

**Comment by jerabaul29** [comment]
Ok, thanks! Guess the values in both kind of files should be identical anyways? Will consider if I keep it or not :) .

**Comment by setmar** [comment]
Yes, I guess so too, but I did not check :)
